import os
import sys
import pandas as pd
import argparse

def calculate_kelly_orders(predictions_csv, bankroll, fraction=0.25):
    if not os.path.exists(predictions_csv):
        print(f"[Error] Could not find predictions file: {predictions_csv}")
        sys.exit(1)
        
    df = pd.read_csv(predictions_csv)
    orders = []

    for index, row in df.iterrows():
        match_name = f"{row['Home Team']} vs {row['Away Team']}"
        
        # 1. Over 2.5 Kelly Math
        ev_over = -1.0
        kelly_over = 0.0
        if row['Odds_Over_25'] > 0:
            ev_over = (row['Prob_Over_25'] * row['Odds_Over_25']) - 1.0
            if ev_over > 0:
                b_over = row['Odds_Over_25'] - 1.0
                kelly_over = ((row['Prob_Over_25'] * b_over) - (1.0 - row['Prob_Over_25'])) / b_over

        # 2. Under 2.5 Kelly Math
        ev_under = -1.0
        kelly_under = 0.0
        if row['Odds_Under_25'] > 0:
            ev_under = (row['Prob_Under_25'] * row['Odds_Under_25']) - 1.0
            if ev_under > 0:
                b_under = row['Odds_Under_25'] - 1.0
                kelly_under = ((row['Prob_Under_25'] * b_under) - (1.0 - row['Prob_Under_25'])) / b_under

        # 3. Find the best actionable bet for the match
        action = "No Bet"
        final_ev = 0.0
        final_kelly = 0.0
        book_odds = 0.0
        model_prob = 0.0
        
        if ev_over > 0 and ev_over > ev_under:
            action = "Over 2.5"
            final_ev = ev_over
            final_kelly = kelly_over
            book_odds = row['Odds_Over_25']
            model_prob = row['Prob_Over_25']
        elif ev_under > 0 and ev_under > ev_over:
            action = "Under 2.5"
            final_ev = ev_under
            final_kelly = kelly_under
            book_odds = row['Odds_Under_25']
            model_prob = row['Prob_Under_25']

        adj_kelly = final_kelly * fraction
        position_size = adj_kelly * bankroll
        
        if position_size > 0:
            orders.append({
                "Match": match_name,
                "Action": action,
                "Prob": round(model_prob, 4),
                "Odds": book_odds,
                "Edge (EV)": f"+{final_ev * 100:.1f}%",
                "Adj_Kelly": f"{adj_kelly * 100:.2f}%",
                "Wager_$": round(position_size, 2)
            })

    df_orders = pd.DataFrame(orders)
    
    print("\n" + "="*80)
    print(f" ACTIONABLE TRADES (Bankroll: ${bankroll:,.2f} | Kelly Fraction: {fraction})")
    print("="*80)
    
    if df_orders.empty:
        print("No profitable +EV bets found. Keep capital protected.")
    else:
        # Sort by largest wager
        df_orders = df_orders.sort_values(by='Wager_$', ascending=False)
        print(df_orders.to_string(index=False))
        
    print("="*80 + "\n")

    # Save orders to CSV
    base_filename = os.path.basename(predictions_csv)
    output_filename = base_filename.replace('_predictions.csv', '_kelly_orders.csv')
    output_filepath = os.path.join('prediction', output_filename)
    
    if not df_orders.empty:
        df_orders.to_csv(output_filepath, index=False)
        print(f"Saved Matchday Orders to: {output_filepath}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Fractional Kelly Position Sizer")
    parser.add_argument("--csv", required=True, help="Path to the predictions CSV file generated by poisson.py")
    parser.add_argument("--bankroll", type=float, default=10000.0, help="Total available capital")
    parser.add_argument("--fraction", type=float, default=0.25, help="Fractional Kelly multiplier (default: 0.25)")
    
    args = parser.parse_args()
    calculate_kelly_orders(args.csv, args.bankroll, args.fraction)